Support setting spdk_tgt log level and flags
longhorn/longhorn-spdk-engine pull request #108
Opened 2024-02-18 16:20 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#7939

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

Deps on https://github.com/longhorn/go-spdk-helper/pull/76
Deps on https://github.com/longhorn/go-spdk-helper/pull/77

2024-02-19 03:16 UTC, innobead requested changes
In general, LGTM. Just a few comments.

2024-02-19 03:16 UTC, innobead commented on proto/spdkrpc/spdk.proto
> +	rpc LogGetFlags(LogGetFlagsRequest) returns (LogGetFlagsResponse);
Fix the incorrect indention formatting.

2024-02-19 03:16 UTC, innobead commented on pkg/spdk/log.go
> +		"service": service,
Is `service` is just for info purpose? will we have any other chances of having another service other than spdk_tgt?

2024-02-19 03:16 UTC, innobead commented on proto/spdkrpc/spdk.proto
> +	string service = 1;
Is `service` required?

2024-02-19 08:49 UTC, innobead commented on pkg/spdk/log.go
> +		"service": service,
That's OK. If you think it's helpful, let's keep it.

2024-02-19 11:17 UTC, derekbit commented
> It seems the PR was not updated yet?

Sorry, I mistakenly requested review.

2024-02-19 15:14 UTC, derekbit commented on proto/spdkrpc/spdk.proto
> +	rpc LogGetFlags(LogGetFlagsRequest) returns (LogGetFlagsResponse);
Fixed. Thank you.

2024-02-20 00:02 UTC, derekbit commented
Rebased and ready to review. cc @innobead

2024-02-20 05:34 UTC, innobead approved these changes

2024-02-20 05:34 UTC, merged