chore: update the outdated README.md
longhorn/longhorn-spdk-engine pull request #259
Opened 2024-12-08 08:56 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue #

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-12-08 15:05 UTC, derekbit commented
@coderabbitai pause

2024-12-10 02:53 UTC, c3y1huang reviewed
Should we also include sections for build status, contribution, license, etc., similar to those in the longhorn-engine and other repos?

2024-12-10 04:04 UTC, derekbit commented
> Should we also include sections for build status, contribution, license, etc., similar to those in the longhorn-engine and other repos?

All are updated. Thank you.

2024-12-10 04:06 UTC, c3y1huang requested changes

2024-12-10 04:06 UTC, c3y1huang commented on README.md
> +Copyright (c) 2014-2024 The Longhorn Authors
```suggestion
Copyright (c) 2022-2024 The Longhorn Authors
```

2024-12-10 04:12 UTC, derekbit commented on README.md
> +Copyright (c) 2014-2024 The Longhorn Authors
Fixed. Thanks.

2024-12-10 04:13 UTC, c3y1huang approved these changes

2024-12-10 04:15 UTC, merged